# Generated by Django 6.0.2 on 2026-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 18)), name='age_must_be_18_or_older'),
        ),
    ]
