# Generated by Django 6.0.2 on 2026-02-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age_must_be_18_or_older'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='age_must_be_18_or_older',
        ),
    ]
